"""Characterization tests for CXA-FL-JELLYFINMCP-02's 9 CCN>50 MediaClient
query-parameter-builder methods, before they are decomposed.

Each targeted method follows the same generated shape: required path
parameters get substituted into the endpoint template, then a long chain
of ``if <arg> is not None: params[<key>] = <arg>`` sets an optional
camelCase query parameter. These tests pin, per method: the endpoint
after path substitution, the snake_case->camelCase key mapping, and that
inclusion is gated on ``is not None`` (not truthiness) so falsy-but
-provided values (False/0/""/[]) survive.
"""

from unittest.mock import MagicMock

from jellyfin_mcp.api.api_client_media import MediaClient


def _make_media_client() -> MediaClient:
    # ApiBase.__init__ probes /System/Info at construction time but swallows
    # connection errors, so an unreachable base_url is safe here.
    return MediaClient(base_url="http://127.0.0.1:1/")


def test_get_trailers_required_only_yields_empty_params():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_trailers()
    client.request.assert_called_once()
    args, kwargs = client.request.call_args
    assert args[0] == "GET"
    assert args[1] == "/Trailers"
    assert kwargs["params"] == {}


def test_get_trailers_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every optional parameter."""
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_trailers(
        user_id="",
        max_official_rating="",
        has_theme_song=False,
        has_theme_video=False,
        has_subtitles=False,
        has_special_feature=False,
        has_trailer=False,
        adjacent_to="",
        parent_index_number=0,
        has_parental_rating=False,
        is_hd=False,
        is4_k=False,
        location_types=[],
        exclude_location_types=[],
        is_missing=False,
        is_unaired=False,
        min_community_rating=0.0,
        min_critic_rating=0.0,
        min_premiere_date="",
        min_date_last_saved="",
        min_date_last_saved_for_user="",
        max_premiere_date="",
        has_overview=False,
        has_imdb_id=False,
        has_tmdb_id=False,
        has_tvdb_id=False,
        is_movie=False,
        is_series=False,
        is_news=False,
        is_kids=False,
        is_sports=False,
        exclude_item_ids=[],
        start_index=0,
        limit=0,
        recursive=False,
        search_term="",
        sort_order=[],
        parent_id="",
        fields=[],
        exclude_item_types=[],
        filters=[],
        is_favorite=False,
        media_types=[],
        image_types=[],
        sort_by=[],
        is_played=False,
        genres=[],
        official_ratings=[],
        tags=[],
        years=[],
        enable_user_data=False,
        image_type_limit=0,
        enable_image_types=[],
        person="",
        person_ids=[],
        person_types=[],
        studios=[],
        artists=[],
        exclude_artist_ids=[],
        artist_ids=[],
        album_artist_ids=[],
        contributing_artist_ids=[],
        albums=[],
        album_ids=[],
        ids=[],
        video_types=[],
        min_official_rating="",
        is_locked=False,
        is_place_holder=False,
        has_official_rating=False,
        collapse_box_set_items=False,
        min_width=0,
        min_height=0,
        max_width=0,
        max_height=0,
        is3_d=False,
        series_status=[],
        name_starts_with_or_greater="",
        name_starts_with="",
        name_less_than="",
        studio_ids=[],
        genre_ids=[],
        enable_total_record_count=False,
        enable_images=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "userId": "",
        "maxOfficialRating": "",
        "hasThemeSong": False,
        "hasThemeVideo": False,
        "hasSubtitles": False,
        "hasSpecialFeature": False,
        "hasTrailer": False,
        "adjacentTo": "",
        "parentIndexNumber": 0,
        "hasParentalRating": False,
        "isHd": False,
        "is4K": False,
        "locationTypes": [],
        "excludeLocationTypes": [],
        "isMissing": False,
        "isUnaired": False,
        "minCommunityRating": 0.0,
        "minCriticRating": 0.0,
        "minPremiereDate": "",
        "minDateLastSaved": "",
        "minDateLastSavedForUser": "",
        "maxPremiereDate": "",
        "hasOverview": False,
        "hasImdbId": False,
        "hasTmdbId": False,
        "hasTvdbId": False,
        "isMovie": False,
        "isSeries": False,
        "isNews": False,
        "isKids": False,
        "isSports": False,
        "excludeItemIds": [],
        "startIndex": 0,
        "limit": 0,
        "recursive": False,
        "searchTerm": "",
        "sortOrder": [],
        "parentId": "",
        "fields": [],
        "excludeItemTypes": [],
        "filters": [],
        "isFavorite": False,
        "mediaTypes": [],
        "imageTypes": [],
        "sortBy": [],
        "isPlayed": False,
        "genres": [],
        "officialRatings": [],
        "tags": [],
        "years": [],
        "enableUserData": False,
        "imageTypeLimit": 0,
        "enableImageTypes": [],
        "person": "",
        "personIds": [],
        "personTypes": [],
        "studios": [],
        "artists": [],
        "excludeArtistIds": [],
        "artistIds": [],
        "albumArtistIds": [],
        "contributingArtistIds": [],
        "albums": [],
        "albumIds": [],
        "ids": [],
        "videoTypes": [],
        "minOfficialRating": "",
        "isLocked": False,
        "isPlaceHolder": False,
        "hasOfficialRating": False,
        "collapseBoxSetItems": False,
        "minWidth": 0,
        "minHeight": 0,
        "maxWidth": 0,
        "maxHeight": 0,
        "is3D": False,
        "seriesStatus": [],
        "nameStartsWithOrGreater": "",
        "nameStartsWith": "",
        "nameLessThan": "",
        "studioIds": [],
        "genreIds": [],
        "enableTotalRecordCount": False,
        "enableImages": False,
    }


def test_get_trailers_all_params_pass_through_with_camel_case_keys():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_trailers(
        user_id="s0",
        max_official_rating="s1",
        has_theme_song=True,
        has_theme_video=True,
        has_subtitles=True,
        has_special_feature=True,
        has_trailer=True,
        adjacent_to="s7",
        parent_index_number=8,
        has_parental_rating=True,
        is_hd=True,
        is4_k=True,
        location_types=["v12"],
        exclude_location_types=["v13"],
        is_missing=True,
        is_unaired=True,
        min_community_rating=16.5,
        min_critic_rating=17.5,
        min_premiere_date="s18",
        min_date_last_saved="s19",
        min_date_last_saved_for_user="s20",
        max_premiere_date="s21",
        has_overview=True,
        has_imdb_id=True,
        has_tmdb_id=True,
        has_tvdb_id=True,
        is_movie=True,
        is_series=True,
        is_news=True,
        is_kids=True,
        is_sports=True,
        exclude_item_ids=["v31"],
        start_index=32,
        limit=33,
        recursive=True,
        search_term="s35",
        sort_order=["v36"],
        parent_id="s37",
        fields=["v38"],
        exclude_item_types=["v39"],
        filters=["v40"],
        is_favorite=True,
        media_types=["v42"],
        image_types=["v43"],
        sort_by=["v44"],
        is_played=True,
        genres=["v46"],
        official_ratings=["v47"],
        tags=["v48"],
        years=["v49"],
        enable_user_data=True,
        image_type_limit=51,
        enable_image_types=["v52"],
        person="s53",
        person_ids=["v54"],
        person_types=["v55"],
        studios=["v56"],
        artists=["v57"],
        exclude_artist_ids=["v58"],
        artist_ids=["v59"],
        album_artist_ids=["v60"],
        contributing_artist_ids=["v61"],
        albums=["v62"],
        album_ids=["v63"],
        ids=["v64"],
        video_types=["v65"],
        min_official_rating="s66",
        is_locked=True,
        is_place_holder=True,
        has_official_rating=True,
        collapse_box_set_items=True,
        min_width=71,
        min_height=72,
        max_width=73,
        max_height=74,
        is3_d=True,
        series_status=["v76"],
        name_starts_with_or_greater="s77",
        name_starts_with="s78",
        name_less_than="s79",
        studio_ids=["v80"],
        genre_ids=["v81"],
        enable_total_record_count=True,
        enable_images=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Trailers",
        params={
            "userId": "s0",
            "maxOfficialRating": "s1",
            "hasThemeSong": True,
            "hasThemeVideo": True,
            "hasSubtitles": True,
            "hasSpecialFeature": True,
            "hasTrailer": True,
            "adjacentTo": "s7",
            "parentIndexNumber": 8,
            "hasParentalRating": True,
            "isHd": True,
            "is4K": True,
            "locationTypes": ["v12"],
            "excludeLocationTypes": ["v13"],
            "isMissing": True,
            "isUnaired": True,
            "minCommunityRating": 16.5,
            "minCriticRating": 17.5,
            "minPremiereDate": "s18",
            "minDateLastSaved": "s19",
            "minDateLastSavedForUser": "s20",
            "maxPremiereDate": "s21",
            "hasOverview": True,
            "hasImdbId": True,
            "hasTmdbId": True,
            "hasTvdbId": True,
            "isMovie": True,
            "isSeries": True,
            "isNews": True,
            "isKids": True,
            "isSports": True,
            "excludeItemIds": ["v31"],
            "startIndex": 32,
            "limit": 33,
            "recursive": True,
            "searchTerm": "s35",
            "sortOrder": ["v36"],
            "parentId": "s37",
            "fields": ["v38"],
            "excludeItemTypes": ["v39"],
            "filters": ["v40"],
            "isFavorite": True,
            "mediaTypes": ["v42"],
            "imageTypes": ["v43"],
            "sortBy": ["v44"],
            "isPlayed": True,
            "genres": ["v46"],
            "officialRatings": ["v47"],
            "tags": ["v48"],
            "years": ["v49"],
            "enableUserData": True,
            "imageTypeLimit": 51,
            "enableImageTypes": ["v52"],
            "person": "s53",
            "personIds": ["v54"],
            "personTypes": ["v55"],
            "studios": ["v56"],
            "artists": ["v57"],
            "excludeArtistIds": ["v58"],
            "artistIds": ["v59"],
            "albumArtistIds": ["v60"],
            "contributingArtistIds": ["v61"],
            "albums": ["v62"],
            "albumIds": ["v63"],
            "ids": ["v64"],
            "videoTypes": ["v65"],
            "minOfficialRating": "s66",
            "isLocked": True,
            "isPlaceHolder": True,
            "hasOfficialRating": True,
            "collapseBoxSetItems": True,
            "minWidth": 71,
            "minHeight": 72,
            "maxWidth": 73,
            "maxHeight": 74,
            "is3D": True,
            "seriesStatus": ["v76"],
            "nameStartsWithOrGreater": "s77",
            "nameStartsWith": "s78",
            "nameLessThan": "s79",
            "studioIds": ["v80"],
            "genreIds": ["v81"],
            "enableTotalRecordCount": True,
            "enableImages": True,
        },
    )

def test_get_hls_video_segment_required_only_yields_empty_params():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_hls_video_segment(item_id="item_id-val", playlist_id="playlist_id-val", segment_id=102, container="container-val")
    client.request.assert_called_once()
    args, kwargs = client.request.call_args
    assert args[0] == "GET"
    assert args[1] == "/Videos/item_id-val/hls1/playlist_id-val/102.container-val"
    assert kwargs["params"] == {}


def test_get_hls_video_segment_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every optional parameter."""
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_hls_video_segment(
        item_id="item_id-val",
        playlist_id="playlist_id-val",
        segment_id=102,
        container="container-val",
        runtime_ticks=0,
        actual_segment_length_ticks=0,
        static=False,
        stream_params="",
        tag="",
        device_profile_id="",
        play_session_id="",
        segment_container="",
        segment_length=0,
        min_segments=0,
        media_source_id="",
        device_id="",
        audio_codec="",
        enable_auto_stream_copy=False,
        allow_video_stream_copy=False,
        allow_audio_stream_copy=False,
        break_on_non_key_frames=False,
        audio_sample_rate=0,
        max_audio_bit_depth=0,
        audio_bit_rate=0,
        audio_channels=0,
        max_audio_channels=0,
        profile="",
        level="",
        framerate=0.0,
        max_framerate=0.0,
        copy_timestamps=False,
        start_time_ticks=0,
        width=0,
        height=0,
        max_width=0,
        max_height=0,
        video_bit_rate=0,
        subtitle_stream_index=0,
        subtitle_method="",
        max_ref_frames=0,
        max_video_bit_depth=0,
        require_avc=False,
        de_interlace=False,
        require_non_anamorphic=False,
        transcoding_max_audio_channels=0,
        cpu_core_limit=0,
        live_stream_id="",
        enable_mpegts_m2_ts_mode=False,
        video_codec="",
        subtitle_codec="",
        transcode_reasons="",
        audio_stream_index=0,
        video_stream_index=0,
        context="",
        stream_options={},
        enable_audio_vbr_encoding=False,
        always_burn_in_subtitle_when_transcoding=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "runtimeTicks": 0,
        "actualSegmentLengthTicks": 0,
        "static": False,
        "params": "",
        "tag": "",
        "deviceProfileId": "",
        "playSessionId": "",
        "segmentContainer": "",
        "segmentLength": 0,
        "minSegments": 0,
        "mediaSourceId": "",
        "deviceId": "",
        "audioCodec": "",
        "enableAutoStreamCopy": False,
        "allowVideoStreamCopy": False,
        "allowAudioStreamCopy": False,
        "breakOnNonKeyFrames": False,
        "audioSampleRate": 0,
        "maxAudioBitDepth": 0,
        "audioBitRate": 0,
        "audioChannels": 0,
        "maxAudioChannels": 0,
        "profile": "",
        "level": "",
        "framerate": 0.0,
        "maxFramerate": 0.0,
        "copyTimestamps": False,
        "startTimeTicks": 0,
        "width": 0,
        "height": 0,
        "maxWidth": 0,
        "maxHeight": 0,
        "videoBitRate": 0,
        "subtitleStreamIndex": 0,
        "subtitleMethod": "",
        "maxRefFrames": 0,
        "maxVideoBitDepth": 0,
        "requireAvc": False,
        "deInterlace": False,
        "requireNonAnamorphic": False,
        "transcodingMaxAudioChannels": 0,
        "cpuCoreLimit": 0,
        "liveStreamId": "",
        "enableMpegtsM2TsMode": False,
        "videoCodec": "",
        "subtitleCodec": "",
        "transcodeReasons": "",
        "audioStreamIndex": 0,
        "videoStreamIndex": 0,
        "context": "",
        "streamOptions": {},
        "enableAudioVbrEncoding": False,
        "alwaysBurnInSubtitleWhenTranscoding": False,
    }


def test_get_hls_video_segment_all_params_pass_through_with_camel_case_keys():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_hls_video_segment(
        item_id="item_id-val",
        playlist_id="playlist_id-val",
        segment_id=102,
        container="container-val",
        runtime_ticks=0,
        actual_segment_length_ticks=1,
        static=True,
        stream_params="s3",
        tag="s4",
        device_profile_id="s5",
        play_session_id="s6",
        segment_container="s7",
        segment_length=8,
        min_segments=9,
        media_source_id="s10",
        device_id="s11",
        audio_codec="s12",
        enable_auto_stream_copy=True,
        allow_video_stream_copy=True,
        allow_audio_stream_copy=True,
        break_on_non_key_frames=True,
        audio_sample_rate=17,
        max_audio_bit_depth=18,
        audio_bit_rate=19,
        audio_channels=20,
        max_audio_channels=21,
        profile="s22",
        level="s23",
        framerate=24.5,
        max_framerate=25.5,
        copy_timestamps=True,
        start_time_ticks=27,
        width=28,
        height=29,
        max_width=30,
        max_height=31,
        video_bit_rate=32,
        subtitle_stream_index=33,
        subtitle_method="s34",
        max_ref_frames=35,
        max_video_bit_depth=36,
        require_avc=True,
        de_interlace=True,
        require_non_anamorphic=True,
        transcoding_max_audio_channels=40,
        cpu_core_limit=41,
        live_stream_id="s42",
        enable_mpegts_m2_ts_mode=True,
        video_codec="s44",
        subtitle_codec="s45",
        transcode_reasons="s46",
        audio_stream_index=47,
        video_stream_index=48,
        context="s49",
        stream_options={"k50": "v50"},
        enable_audio_vbr_encoding=True,
        always_burn_in_subtitle_when_transcoding=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Videos/item_id-val/hls1/playlist_id-val/102.container-val",
        params={
            "runtimeTicks": 0,
            "actualSegmentLengthTicks": 1,
            "static": True,
            "params": "s3",
            "tag": "s4",
            "deviceProfileId": "s5",
            "playSessionId": "s6",
            "segmentContainer": "s7",
            "segmentLength": 8,
            "minSegments": 9,
            "mediaSourceId": "s10",
            "deviceId": "s11",
            "audioCodec": "s12",
            "enableAutoStreamCopy": True,
            "allowVideoStreamCopy": True,
            "allowAudioStreamCopy": True,
            "breakOnNonKeyFrames": True,
            "audioSampleRate": 17,
            "maxAudioBitDepth": 18,
            "audioBitRate": 19,
            "audioChannels": 20,
            "maxAudioChannels": 21,
            "profile": "s22",
            "level": "s23",
            "framerate": 24.5,
            "maxFramerate": 25.5,
            "copyTimestamps": True,
            "startTimeTicks": 27,
            "width": 28,
            "height": 29,
            "maxWidth": 30,
            "maxHeight": 31,
            "videoBitRate": 32,
            "subtitleStreamIndex": 33,
            "subtitleMethod": "s34",
            "maxRefFrames": 35,
            "maxVideoBitDepth": 36,
            "requireAvc": True,
            "deInterlace": True,
            "requireNonAnamorphic": True,
            "transcodingMaxAudioChannels": 40,
            "cpuCoreLimit": 41,
            "liveStreamId": "s42",
            "enableMpegtsM2TsMode": True,
            "videoCodec": "s44",
            "subtitleCodec": "s45",
            "transcodeReasons": "s46",
            "audioStreamIndex": 47,
            "videoStreamIndex": 48,
            "context": "s49",
            "streamOptions": {"k50": "v50"},
            "enableAudioVbrEncoding": True,
            "alwaysBurnInSubtitleWhenTranscoding": True,
        },
    )

def test_get_live_hls_stream_required_only_yields_empty_params():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_live_hls_stream(item_id="item_id-val")
    client.request.assert_called_once()
    args, kwargs = client.request.call_args
    assert args[0] == "GET"
    assert args[1] == "/Videos/item_id-val/live.m3u8"
    assert kwargs["params"] == {}


def test_get_live_hls_stream_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every optional parameter."""
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_live_hls_stream(
        item_id="item_id-val",
        container="",
        static=False,
        stream_params="",
        tag="",
        device_profile_id="",
        play_session_id="",
        segment_container="",
        segment_length=0,
        min_segments=0,
        media_source_id="",
        device_id="",
        audio_codec="",
        enable_auto_stream_copy=False,
        allow_video_stream_copy=False,
        allow_audio_stream_copy=False,
        break_on_non_key_frames=False,
        audio_sample_rate=0,
        max_audio_bit_depth=0,
        audio_bit_rate=0,
        audio_channels=0,
        max_audio_channels=0,
        profile="",
        level="",
        framerate=0.0,
        max_framerate=0.0,
        copy_timestamps=False,
        start_time_ticks=0,
        width=0,
        height=0,
        video_bit_rate=0,
        subtitle_stream_index=0,
        subtitle_method="",
        max_ref_frames=0,
        max_video_bit_depth=0,
        require_avc=False,
        de_interlace=False,
        require_non_anamorphic=False,
        transcoding_max_audio_channels=0,
        cpu_core_limit=0,
        live_stream_id="",
        enable_mpegts_m2_ts_mode=False,
        video_codec="",
        subtitle_codec="",
        transcode_reasons="",
        audio_stream_index=0,
        video_stream_index=0,
        context="",
        stream_options={},
        max_width=0,
        max_height=0,
        enable_subtitles_in_manifest=False,
        enable_audio_vbr_encoding=False,
        always_burn_in_subtitle_when_transcoding=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "container": "",
        "static": False,
        "params": "",
        "tag": "",
        "deviceProfileId": "",
        "playSessionId": "",
        "segmentContainer": "",
        "segmentLength": 0,
        "minSegments": 0,
        "mediaSourceId": "",
        "deviceId": "",
        "audioCodec": "",
        "enableAutoStreamCopy": False,
        "allowVideoStreamCopy": False,
        "allowAudioStreamCopy": False,
        "breakOnNonKeyFrames": False,
        "audioSampleRate": 0,
        "maxAudioBitDepth": 0,
        "audioBitRate": 0,
        "audioChannels": 0,
        "maxAudioChannels": 0,
        "profile": "",
        "level": "",
        "framerate": 0.0,
        "maxFramerate": 0.0,
        "copyTimestamps": False,
        "startTimeTicks": 0,
        "width": 0,
        "height": 0,
        "videoBitRate": 0,
        "subtitleStreamIndex": 0,
        "subtitleMethod": "",
        "maxRefFrames": 0,
        "maxVideoBitDepth": 0,
        "requireAvc": False,
        "deInterlace": False,
        "requireNonAnamorphic": False,
        "transcodingMaxAudioChannels": 0,
        "cpuCoreLimit": 0,
        "liveStreamId": "",
        "enableMpegtsM2TsMode": False,
        "videoCodec": "",
        "subtitleCodec": "",
        "transcodeReasons": "",
        "audioStreamIndex": 0,
        "videoStreamIndex": 0,
        "context": "",
        "streamOptions": {},
        "maxWidth": 0,
        "maxHeight": 0,
        "enableSubtitlesInManifest": False,
        "enableAudioVbrEncoding": False,
        "alwaysBurnInSubtitleWhenTranscoding": False,
    }


def test_get_live_hls_stream_all_params_pass_through_with_camel_case_keys():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_live_hls_stream(
        item_id="item_id-val",
        container="s0",
        static=True,
        stream_params="s2",
        tag="s3",
        device_profile_id="s4",
        play_session_id="s5",
        segment_container="s6",
        segment_length=7,
        min_segments=8,
        media_source_id="s9",
        device_id="s10",
        audio_codec="s11",
        enable_auto_stream_copy=True,
        allow_video_stream_copy=True,
        allow_audio_stream_copy=True,
        break_on_non_key_frames=True,
        audio_sample_rate=16,
        max_audio_bit_depth=17,
        audio_bit_rate=18,
        audio_channels=19,
        max_audio_channels=20,
        profile="s21",
        level="s22",
        framerate=23.5,
        max_framerate=24.5,
        copy_timestamps=True,
        start_time_ticks=26,
        width=27,
        height=28,
        video_bit_rate=29,
        subtitle_stream_index=30,
        subtitle_method="s31",
        max_ref_frames=32,
        max_video_bit_depth=33,
        require_avc=True,
        de_interlace=True,
        require_non_anamorphic=True,
        transcoding_max_audio_channels=37,
        cpu_core_limit=38,
        live_stream_id="s39",
        enable_mpegts_m2_ts_mode=True,
        video_codec="s41",
        subtitle_codec="s42",
        transcode_reasons="s43",
        audio_stream_index=44,
        video_stream_index=45,
        context="s46",
        stream_options={"k47": "v47"},
        max_width=48,
        max_height=49,
        enable_subtitles_in_manifest=True,
        enable_audio_vbr_encoding=True,
        always_burn_in_subtitle_when_transcoding=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Videos/item_id-val/live.m3u8",
        params={
            "container": "s0",
            "static": True,
            "params": "s2",
            "tag": "s3",
            "deviceProfileId": "s4",
            "playSessionId": "s5",
            "segmentContainer": "s6",
            "segmentLength": 7,
            "minSegments": 8,
            "mediaSourceId": "s9",
            "deviceId": "s10",
            "audioCodec": "s11",
            "enableAutoStreamCopy": True,
            "allowVideoStreamCopy": True,
            "allowAudioStreamCopy": True,
            "breakOnNonKeyFrames": True,
            "audioSampleRate": 16,
            "maxAudioBitDepth": 17,
            "audioBitRate": 18,
            "audioChannels": 19,
            "maxAudioChannels": 20,
            "profile": "s21",
            "level": "s22",
            "framerate": 23.5,
            "maxFramerate": 24.5,
            "copyTimestamps": True,
            "startTimeTicks": 26,
            "width": 27,
            "height": 28,
            "videoBitRate": 29,
            "subtitleStreamIndex": 30,
            "subtitleMethod": "s31",
            "maxRefFrames": 32,
            "maxVideoBitDepth": 33,
            "requireAvc": True,
            "deInterlace": True,
            "requireNonAnamorphic": True,
            "transcodingMaxAudioChannels": 37,
            "cpuCoreLimit": 38,
            "liveStreamId": "s39",
            "enableMpegtsM2TsMode": True,
            "videoCodec": "s41",
            "subtitleCodec": "s42",
            "transcodeReasons": "s43",
            "audioStreamIndex": 44,
            "videoStreamIndex": 45,
            "context": "s46",
            "streamOptions": {"k47": "v47"},
            "maxWidth": 48,
            "maxHeight": 49,
            "enableSubtitlesInManifest": True,
            "enableAudioVbrEncoding": True,
            "alwaysBurnInSubtitleWhenTranscoding": True,
        },
    )

def test_get_master_hls_video_playlist_required_only_yields_empty_params():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_master_hls_video_playlist(item_id="item_id-val")
    client.request.assert_called_once()
    args, kwargs = client.request.call_args
    assert args[0] == "GET"
    assert args[1] == "/Videos/item_id-val/master.m3u8"
    assert kwargs["params"] == {}


def test_get_master_hls_video_playlist_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every optional parameter."""
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_master_hls_video_playlist(
        item_id="item_id-val",
        static=False,
        stream_params="",
        tag="",
        device_profile_id="",
        play_session_id="",
        segment_container="",
        segment_length=0,
        min_segments=0,
        media_source_id="",
        device_id="",
        audio_codec="",
        enable_auto_stream_copy=False,
        allow_video_stream_copy=False,
        allow_audio_stream_copy=False,
        break_on_non_key_frames=False,
        audio_sample_rate=0,
        max_audio_bit_depth=0,
        audio_bit_rate=0,
        audio_channels=0,
        max_audio_channels=0,
        profile="",
        level="",
        framerate=0.0,
        max_framerate=0.0,
        copy_timestamps=False,
        start_time_ticks=0,
        width=0,
        height=0,
        max_width=0,
        max_height=0,
        video_bit_rate=0,
        subtitle_stream_index=0,
        subtitle_method="",
        max_ref_frames=0,
        max_video_bit_depth=0,
        require_avc=False,
        de_interlace=False,
        require_non_anamorphic=False,
        transcoding_max_audio_channels=0,
        cpu_core_limit=0,
        live_stream_id="",
        enable_mpegts_m2_ts_mode=False,
        video_codec="",
        subtitle_codec="",
        transcode_reasons="",
        audio_stream_index=0,
        video_stream_index=0,
        context="",
        stream_options={},
        enable_adaptive_bitrate_streaming=False,
        enable_trickplay=False,
        enable_audio_vbr_encoding=False,
        always_burn_in_subtitle_when_transcoding=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "static": False,
        "params": "",
        "tag": "",
        "deviceProfileId": "",
        "playSessionId": "",
        "segmentContainer": "",
        "segmentLength": 0,
        "minSegments": 0,
        "mediaSourceId": "",
        "deviceId": "",
        "audioCodec": "",
        "enableAutoStreamCopy": False,
        "allowVideoStreamCopy": False,
        "allowAudioStreamCopy": False,
        "breakOnNonKeyFrames": False,
        "audioSampleRate": 0,
        "maxAudioBitDepth": 0,
        "audioBitRate": 0,
        "audioChannels": 0,
        "maxAudioChannels": 0,
        "profile": "",
        "level": "",
        "framerate": 0.0,
        "maxFramerate": 0.0,
        "copyTimestamps": False,
        "startTimeTicks": 0,
        "width": 0,
        "height": 0,
        "maxWidth": 0,
        "maxHeight": 0,
        "videoBitRate": 0,
        "subtitleStreamIndex": 0,
        "subtitleMethod": "",
        "maxRefFrames": 0,
        "maxVideoBitDepth": 0,
        "requireAvc": False,
        "deInterlace": False,
        "requireNonAnamorphic": False,
        "transcodingMaxAudioChannels": 0,
        "cpuCoreLimit": 0,
        "liveStreamId": "",
        "enableMpegtsM2TsMode": False,
        "videoCodec": "",
        "subtitleCodec": "",
        "transcodeReasons": "",
        "audioStreamIndex": 0,
        "videoStreamIndex": 0,
        "context": "",
        "streamOptions": {},
        "enableAdaptiveBitrateStreaming": False,
        "enableTrickplay": False,
        "enableAudioVbrEncoding": False,
        "alwaysBurnInSubtitleWhenTranscoding": False,
    }


def test_get_master_hls_video_playlist_all_params_pass_through_with_camel_case_keys():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_master_hls_video_playlist(
        item_id="item_id-val",
        static=True,
        stream_params="s1",
        tag="s2",
        device_profile_id="s3",
        play_session_id="s4",
        segment_container="s5",
        segment_length=6,
        min_segments=7,
        media_source_id="s8",
        device_id="s9",
        audio_codec="s10",
        enable_auto_stream_copy=True,
        allow_video_stream_copy=True,
        allow_audio_stream_copy=True,
        break_on_non_key_frames=True,
        audio_sample_rate=15,
        max_audio_bit_depth=16,
        audio_bit_rate=17,
        audio_channels=18,
        max_audio_channels=19,
        profile="s20",
        level="s21",
        framerate=22.5,
        max_framerate=23.5,
        copy_timestamps=True,
        start_time_ticks=25,
        width=26,
        height=27,
        max_width=28,
        max_height=29,
        video_bit_rate=30,
        subtitle_stream_index=31,
        subtitle_method="s32",
        max_ref_frames=33,
        max_video_bit_depth=34,
        require_avc=True,
        de_interlace=True,
        require_non_anamorphic=True,
        transcoding_max_audio_channels=38,
        cpu_core_limit=39,
        live_stream_id="s40",
        enable_mpegts_m2_ts_mode=True,
        video_codec="s42",
        subtitle_codec="s43",
        transcode_reasons="s44",
        audio_stream_index=45,
        video_stream_index=46,
        context="s47",
        stream_options={"k48": "v48"},
        enable_adaptive_bitrate_streaming=True,
        enable_trickplay=True,
        enable_audio_vbr_encoding=True,
        always_burn_in_subtitle_when_transcoding=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Videos/item_id-val/master.m3u8",
        params={
            "static": True,
            "params": "s1",
            "tag": "s2",
            "deviceProfileId": "s3",
            "playSessionId": "s4",
            "segmentContainer": "s5",
            "segmentLength": 6,
            "minSegments": 7,
            "mediaSourceId": "s8",
            "deviceId": "s9",
            "audioCodec": "s10",
            "enableAutoStreamCopy": True,
            "allowVideoStreamCopy": True,
            "allowAudioStreamCopy": True,
            "breakOnNonKeyFrames": True,
            "audioSampleRate": 15,
            "maxAudioBitDepth": 16,
            "audioBitRate": 17,
            "audioChannels": 18,
            "maxAudioChannels": 19,
            "profile": "s20",
            "level": "s21",
            "framerate": 22.5,
            "maxFramerate": 23.5,
            "copyTimestamps": True,
            "startTimeTicks": 25,
            "width": 26,
            "height": 27,
            "maxWidth": 28,
            "maxHeight": 29,
            "videoBitRate": 30,
            "subtitleStreamIndex": 31,
            "subtitleMethod": "s32",
            "maxRefFrames": 33,
            "maxVideoBitDepth": 34,
            "requireAvc": True,
            "deInterlace": True,
            "requireNonAnamorphic": True,
            "transcodingMaxAudioChannels": 38,
            "cpuCoreLimit": 39,
            "liveStreamId": "s40",
            "enableMpegtsM2TsMode": True,
            "videoCodec": "s42",
            "subtitleCodec": "s43",
            "transcodeReasons": "s44",
            "audioStreamIndex": 45,
            "videoStreamIndex": 46,
            "context": "s47",
            "streamOptions": {"k48": "v48"},
            "enableAdaptiveBitrateStreaming": True,
            "enableTrickplay": True,
            "enableAudioVbrEncoding": True,
            "alwaysBurnInSubtitleWhenTranscoding": True,
        },
    )

def test_get_hls_audio_segment_required_only_yields_empty_params():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_hls_audio_segment(item_id="item_id-val", playlist_id="playlist_id-val", segment_id=102, container="container-val")
    client.request.assert_called_once()
    args, kwargs = client.request.call_args
    assert args[0] == "GET"
    assert args[1] == "/Audio/item_id-val/hls1/playlist_id-val/102.container-val"
    assert kwargs["params"] == {}


def test_get_hls_audio_segment_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every optional parameter."""
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_hls_audio_segment(
        item_id="item_id-val",
        playlist_id="playlist_id-val",
        segment_id=102,
        container="container-val",
        runtime_ticks=0,
        actual_segment_length_ticks=0,
        static=False,
        stream_params="",
        tag="",
        device_profile_id="",
        play_session_id="",
        segment_container="",
        segment_length=0,
        min_segments=0,
        media_source_id="",
        device_id="",
        audio_codec="",
        enable_auto_stream_copy=False,
        allow_video_stream_copy=False,
        allow_audio_stream_copy=False,
        break_on_non_key_frames=False,
        audio_sample_rate=0,
        max_audio_bit_depth=0,
        max_streaming_bitrate=0,
        audio_bit_rate=0,
        audio_channels=0,
        max_audio_channels=0,
        profile="",
        level="",
        framerate=0.0,
        max_framerate=0.0,
        copy_timestamps=False,
        start_time_ticks=0,
        width=0,
        height=0,
        video_bit_rate=0,
        subtitle_stream_index=0,
        subtitle_method="",
        max_ref_frames=0,
        max_video_bit_depth=0,
        require_avc=False,
        de_interlace=False,
        require_non_anamorphic=False,
        transcoding_max_audio_channels=0,
        cpu_core_limit=0,
        live_stream_id="",
        enable_mpegts_m2_ts_mode=False,
        video_codec="",
        subtitle_codec="",
        transcode_reasons="",
        audio_stream_index=0,
        video_stream_index=0,
        context="",
        stream_options={},
        enable_audio_vbr_encoding=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "runtimeTicks": 0,
        "actualSegmentLengthTicks": 0,
        "static": False,
        "params": "",
        "tag": "",
        "deviceProfileId": "",
        "playSessionId": "",
        "segmentContainer": "",
        "segmentLength": 0,
        "minSegments": 0,
        "mediaSourceId": "",
        "deviceId": "",
        "audioCodec": "",
        "enableAutoStreamCopy": False,
        "allowVideoStreamCopy": False,
        "allowAudioStreamCopy": False,
        "breakOnNonKeyFrames": False,
        "audioSampleRate": 0,
        "maxAudioBitDepth": 0,
        "maxStreamingBitrate": 0,
        "audioBitRate": 0,
        "audioChannels": 0,
        "maxAudioChannels": 0,
        "profile": "",
        "level": "",
        "framerate": 0.0,
        "maxFramerate": 0.0,
        "copyTimestamps": False,
        "startTimeTicks": 0,
        "width": 0,
        "height": 0,
        "videoBitRate": 0,
        "subtitleStreamIndex": 0,
        "subtitleMethod": "",
        "maxRefFrames": 0,
        "maxVideoBitDepth": 0,
        "requireAvc": False,
        "deInterlace": False,
        "requireNonAnamorphic": False,
        "transcodingMaxAudioChannels": 0,
        "cpuCoreLimit": 0,
        "liveStreamId": "",
        "enableMpegtsM2TsMode": False,
        "videoCodec": "",
        "subtitleCodec": "",
        "transcodeReasons": "",
        "audioStreamIndex": 0,
        "videoStreamIndex": 0,
        "context": "",
        "streamOptions": {},
        "enableAudioVbrEncoding": False,
    }


def test_get_hls_audio_segment_all_params_pass_through_with_camel_case_keys():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_hls_audio_segment(
        item_id="item_id-val",
        playlist_id="playlist_id-val",
        segment_id=102,
        container="container-val",
        runtime_ticks=0,
        actual_segment_length_ticks=1,
        static=True,
        stream_params="s3",
        tag="s4",
        device_profile_id="s5",
        play_session_id="s6",
        segment_container="s7",
        segment_length=8,
        min_segments=9,
        media_source_id="s10",
        device_id="s11",
        audio_codec="s12",
        enable_auto_stream_copy=True,
        allow_video_stream_copy=True,
        allow_audio_stream_copy=True,
        break_on_non_key_frames=True,
        audio_sample_rate=17,
        max_audio_bit_depth=18,
        max_streaming_bitrate=19,
        audio_bit_rate=20,
        audio_channels=21,
        max_audio_channels=22,
        profile="s23",
        level="s24",
        framerate=25.5,
        max_framerate=26.5,
        copy_timestamps=True,
        start_time_ticks=28,
        width=29,
        height=30,
        video_bit_rate=31,
        subtitle_stream_index=32,
        subtitle_method="s33",
        max_ref_frames=34,
        max_video_bit_depth=35,
        require_avc=True,
        de_interlace=True,
        require_non_anamorphic=True,
        transcoding_max_audio_channels=39,
        cpu_core_limit=40,
        live_stream_id="s41",
        enable_mpegts_m2_ts_mode=True,
        video_codec="s43",
        subtitle_codec="s44",
        transcode_reasons="s45",
        audio_stream_index=46,
        video_stream_index=47,
        context="s48",
        stream_options={"k49": "v49"},
        enable_audio_vbr_encoding=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Audio/item_id-val/hls1/playlist_id-val/102.container-val",
        params={
            "runtimeTicks": 0,
            "actualSegmentLengthTicks": 1,
            "static": True,
            "params": "s3",
            "tag": "s4",
            "deviceProfileId": "s5",
            "playSessionId": "s6",
            "segmentContainer": "s7",
            "segmentLength": 8,
            "minSegments": 9,
            "mediaSourceId": "s10",
            "deviceId": "s11",
            "audioCodec": "s12",
            "enableAutoStreamCopy": True,
            "allowVideoStreamCopy": True,
            "allowAudioStreamCopy": True,
            "breakOnNonKeyFrames": True,
            "audioSampleRate": 17,
            "maxAudioBitDepth": 18,
            "maxStreamingBitrate": 19,
            "audioBitRate": 20,
            "audioChannels": 21,
            "maxAudioChannels": 22,
            "profile": "s23",
            "level": "s24",
            "framerate": 25.5,
            "maxFramerate": 26.5,
            "copyTimestamps": True,
            "startTimeTicks": 28,
            "width": 29,
            "height": 30,
            "videoBitRate": 31,
            "subtitleStreamIndex": 32,
            "subtitleMethod": "s33",
            "maxRefFrames": 34,
            "maxVideoBitDepth": 35,
            "requireAvc": True,
            "deInterlace": True,
            "requireNonAnamorphic": True,
            "transcodingMaxAudioChannels": 39,
            "cpuCoreLimit": 40,
            "liveStreamId": "s41",
            "enableMpegtsM2TsMode": True,
            "videoCodec": "s43",
            "subtitleCodec": "s44",
            "transcodeReasons": "s45",
            "audioStreamIndex": 46,
            "videoStreamIndex": 47,
            "context": "s48",
            "streamOptions": {"k49": "v49"},
            "enableAudioVbrEncoding": True,
        },
    )

def test_get_variant_hls_video_playlist_required_only_yields_empty_params():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_variant_hls_video_playlist(item_id="item_id-val")
    client.request.assert_called_once()
    args, kwargs = client.request.call_args
    assert args[0] == "GET"
    assert args[1] == "/Videos/item_id-val/main.m3u8"
    assert kwargs["params"] == {}


def test_get_variant_hls_video_playlist_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every optional parameter."""
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_variant_hls_video_playlist(
        item_id="item_id-val",
        static=False,
        stream_params="",
        tag="",
        device_profile_id="",
        play_session_id="",
        segment_container="",
        segment_length=0,
        min_segments=0,
        media_source_id="",
        device_id="",
        audio_codec="",
        enable_auto_stream_copy=False,
        allow_video_stream_copy=False,
        allow_audio_stream_copy=False,
        break_on_non_key_frames=False,
        audio_sample_rate=0,
        max_audio_bit_depth=0,
        audio_bit_rate=0,
        audio_channels=0,
        max_audio_channels=0,
        profile="",
        level="",
        framerate=0.0,
        max_framerate=0.0,
        copy_timestamps=False,
        start_time_ticks=0,
        width=0,
        height=0,
        max_width=0,
        max_height=0,
        video_bit_rate=0,
        subtitle_stream_index=0,
        subtitle_method="",
        max_ref_frames=0,
        max_video_bit_depth=0,
        require_avc=False,
        de_interlace=False,
        require_non_anamorphic=False,
        transcoding_max_audio_channels=0,
        cpu_core_limit=0,
        live_stream_id="",
        enable_mpegts_m2_ts_mode=False,
        video_codec="",
        subtitle_codec="",
        transcode_reasons="",
        audio_stream_index=0,
        video_stream_index=0,
        context="",
        stream_options={},
        enable_audio_vbr_encoding=False,
        always_burn_in_subtitle_when_transcoding=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "static": False,
        "params": "",
        "tag": "",
        "deviceProfileId": "",
        "playSessionId": "",
        "segmentContainer": "",
        "segmentLength": 0,
        "minSegments": 0,
        "mediaSourceId": "",
        "deviceId": "",
        "audioCodec": "",
        "enableAutoStreamCopy": False,
        "allowVideoStreamCopy": False,
        "allowAudioStreamCopy": False,
        "breakOnNonKeyFrames": False,
        "audioSampleRate": 0,
        "maxAudioBitDepth": 0,
        "audioBitRate": 0,
        "audioChannels": 0,
        "maxAudioChannels": 0,
        "profile": "",
        "level": "",
        "framerate": 0.0,
        "maxFramerate": 0.0,
        "copyTimestamps": False,
        "startTimeTicks": 0,
        "width": 0,
        "height": 0,
        "maxWidth": 0,
        "maxHeight": 0,
        "videoBitRate": 0,
        "subtitleStreamIndex": 0,
        "subtitleMethod": "",
        "maxRefFrames": 0,
        "maxVideoBitDepth": 0,
        "requireAvc": False,
        "deInterlace": False,
        "requireNonAnamorphic": False,
        "transcodingMaxAudioChannels": 0,
        "cpuCoreLimit": 0,
        "liveStreamId": "",
        "enableMpegtsM2TsMode": False,
        "videoCodec": "",
        "subtitleCodec": "",
        "transcodeReasons": "",
        "audioStreamIndex": 0,
        "videoStreamIndex": 0,
        "context": "",
        "streamOptions": {},
        "enableAudioVbrEncoding": False,
        "alwaysBurnInSubtitleWhenTranscoding": False,
    }


def test_get_variant_hls_video_playlist_all_params_pass_through_with_camel_case_keys():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_variant_hls_video_playlist(
        item_id="item_id-val",
        static=True,
        stream_params="s1",
        tag="s2",
        device_profile_id="s3",
        play_session_id="s4",
        segment_container="s5",
        segment_length=6,
        min_segments=7,
        media_source_id="s8",
        device_id="s9",
        audio_codec="s10",
        enable_auto_stream_copy=True,
        allow_video_stream_copy=True,
        allow_audio_stream_copy=True,
        break_on_non_key_frames=True,
        audio_sample_rate=15,
        max_audio_bit_depth=16,
        audio_bit_rate=17,
        audio_channels=18,
        max_audio_channels=19,
        profile="s20",
        level="s21",
        framerate=22.5,
        max_framerate=23.5,
        copy_timestamps=True,
        start_time_ticks=25,
        width=26,
        height=27,
        max_width=28,
        max_height=29,
        video_bit_rate=30,
        subtitle_stream_index=31,
        subtitle_method="s32",
        max_ref_frames=33,
        max_video_bit_depth=34,
        require_avc=True,
        de_interlace=True,
        require_non_anamorphic=True,
        transcoding_max_audio_channels=38,
        cpu_core_limit=39,
        live_stream_id="s40",
        enable_mpegts_m2_ts_mode=True,
        video_codec="s42",
        subtitle_codec="s43",
        transcode_reasons="s44",
        audio_stream_index=45,
        video_stream_index=46,
        context="s47",
        stream_options={"k48": "v48"},
        enable_audio_vbr_encoding=True,
        always_burn_in_subtitle_when_transcoding=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Videos/item_id-val/main.m3u8",
        params={
            "static": True,
            "params": "s1",
            "tag": "s2",
            "deviceProfileId": "s3",
            "playSessionId": "s4",
            "segmentContainer": "s5",
            "segmentLength": 6,
            "minSegments": 7,
            "mediaSourceId": "s8",
            "deviceId": "s9",
            "audioCodec": "s10",
            "enableAutoStreamCopy": True,
            "allowVideoStreamCopy": True,
            "allowAudioStreamCopy": True,
            "breakOnNonKeyFrames": True,
            "audioSampleRate": 15,
            "maxAudioBitDepth": 16,
            "audioBitRate": 17,
            "audioChannels": 18,
            "maxAudioChannels": 19,
            "profile": "s20",
            "level": "s21",
            "framerate": 22.5,
            "maxFramerate": 23.5,
            "copyTimestamps": True,
            "startTimeTicks": 25,
            "width": 26,
            "height": 27,
            "maxWidth": 28,
            "maxHeight": 29,
            "videoBitRate": 30,
            "subtitleStreamIndex": 31,
            "subtitleMethod": "s32",
            "maxRefFrames": 33,
            "maxVideoBitDepth": 34,
            "requireAvc": True,
            "deInterlace": True,
            "requireNonAnamorphic": True,
            "transcodingMaxAudioChannels": 38,
            "cpuCoreLimit": 39,
            "liveStreamId": "s40",
            "enableMpegtsM2TsMode": True,
            "videoCodec": "s42",
            "subtitleCodec": "s43",
            "transcodeReasons": "s44",
            "audioStreamIndex": 45,
            "videoStreamIndex": 46,
            "context": "s47",
            "streamOptions": {"k48": "v48"},
            "enableAudioVbrEncoding": True,
            "alwaysBurnInSubtitleWhenTranscoding": True,
        },
    )

def test_get_video_stream_required_only_yields_empty_params():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_video_stream(item_id="item_id-val")
    client.request.assert_called_once()
    args, kwargs = client.request.call_args
    assert args[0] == "GET"
    assert args[1] == "/Videos/item_id-val/stream"
    assert kwargs["params"] == {}


def test_get_video_stream_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every optional parameter."""
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_video_stream(
        item_id="item_id-val",
        container="",
        static=False,
        stream_params="",
        tag="",
        device_profile_id="",
        play_session_id="",
        segment_container="",
        segment_length=0,
        min_segments=0,
        media_source_id="",
        device_id="",
        audio_codec="",
        enable_auto_stream_copy=False,
        allow_video_stream_copy=False,
        allow_audio_stream_copy=False,
        break_on_non_key_frames=False,
        audio_sample_rate=0,
        max_audio_bit_depth=0,
        audio_bit_rate=0,
        audio_channels=0,
        max_audio_channels=0,
        profile="",
        level="",
        framerate=0.0,
        max_framerate=0.0,
        copy_timestamps=False,
        start_time_ticks=0,
        width=0,
        height=0,
        max_width=0,
        max_height=0,
        video_bit_rate=0,
        subtitle_stream_index=0,
        subtitle_method="",
        max_ref_frames=0,
        max_video_bit_depth=0,
        require_avc=False,
        de_interlace=False,
        require_non_anamorphic=False,
        transcoding_max_audio_channels=0,
        cpu_core_limit=0,
        live_stream_id="",
        enable_mpegts_m2_ts_mode=False,
        video_codec="",
        subtitle_codec="",
        transcode_reasons="",
        audio_stream_index=0,
        video_stream_index=0,
        context="",
        stream_options={},
        enable_audio_vbr_encoding=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "container": "",
        "static": False,
        "params": "",
        "tag": "",
        "deviceProfileId": "",
        "playSessionId": "",
        "segmentContainer": "",
        "segmentLength": 0,
        "minSegments": 0,
        "mediaSourceId": "",
        "deviceId": "",
        "audioCodec": "",
        "enableAutoStreamCopy": False,
        "allowVideoStreamCopy": False,
        "allowAudioStreamCopy": False,
        "breakOnNonKeyFrames": False,
        "audioSampleRate": 0,
        "maxAudioBitDepth": 0,
        "audioBitRate": 0,
        "audioChannels": 0,
        "maxAudioChannels": 0,
        "profile": "",
        "level": "",
        "framerate": 0.0,
        "maxFramerate": 0.0,
        "copyTimestamps": False,
        "startTimeTicks": 0,
        "width": 0,
        "height": 0,
        "maxWidth": 0,
        "maxHeight": 0,
        "videoBitRate": 0,
        "subtitleStreamIndex": 0,
        "subtitleMethod": "",
        "maxRefFrames": 0,
        "maxVideoBitDepth": 0,
        "requireAvc": False,
        "deInterlace": False,
        "requireNonAnamorphic": False,
        "transcodingMaxAudioChannels": 0,
        "cpuCoreLimit": 0,
        "liveStreamId": "",
        "enableMpegtsM2TsMode": False,
        "videoCodec": "",
        "subtitleCodec": "",
        "transcodeReasons": "",
        "audioStreamIndex": 0,
        "videoStreamIndex": 0,
        "context": "",
        "streamOptions": {},
        "enableAudioVbrEncoding": False,
    }


def test_get_video_stream_all_params_pass_through_with_camel_case_keys():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_video_stream(
        item_id="item_id-val",
        container="s0",
        static=True,
        stream_params="s2",
        tag="s3",
        device_profile_id="s4",
        play_session_id="s5",
        segment_container="s6",
        segment_length=7,
        min_segments=8,
        media_source_id="s9",
        device_id="s10",
        audio_codec="s11",
        enable_auto_stream_copy=True,
        allow_video_stream_copy=True,
        allow_audio_stream_copy=True,
        break_on_non_key_frames=True,
        audio_sample_rate=16,
        max_audio_bit_depth=17,
        audio_bit_rate=18,
        audio_channels=19,
        max_audio_channels=20,
        profile="s21",
        level="s22",
        framerate=23.5,
        max_framerate=24.5,
        copy_timestamps=True,
        start_time_ticks=26,
        width=27,
        height=28,
        max_width=29,
        max_height=30,
        video_bit_rate=31,
        subtitle_stream_index=32,
        subtitle_method="s33",
        max_ref_frames=34,
        max_video_bit_depth=35,
        require_avc=True,
        de_interlace=True,
        require_non_anamorphic=True,
        transcoding_max_audio_channels=39,
        cpu_core_limit=40,
        live_stream_id="s41",
        enable_mpegts_m2_ts_mode=True,
        video_codec="s43",
        subtitle_codec="s44",
        transcode_reasons="s45",
        audio_stream_index=46,
        video_stream_index=47,
        context="s48",
        stream_options={"k49": "v49"},
        enable_audio_vbr_encoding=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Videos/item_id-val/stream",
        params={
            "container": "s0",
            "static": True,
            "params": "s2",
            "tag": "s3",
            "deviceProfileId": "s4",
            "playSessionId": "s5",
            "segmentContainer": "s6",
            "segmentLength": 7,
            "minSegments": 8,
            "mediaSourceId": "s9",
            "deviceId": "s10",
            "audioCodec": "s11",
            "enableAutoStreamCopy": True,
            "allowVideoStreamCopy": True,
            "allowAudioStreamCopy": True,
            "breakOnNonKeyFrames": True,
            "audioSampleRate": 16,
            "maxAudioBitDepth": 17,
            "audioBitRate": 18,
            "audioChannels": 19,
            "maxAudioChannels": 20,
            "profile": "s21",
            "level": "s22",
            "framerate": 23.5,
            "maxFramerate": 24.5,
            "copyTimestamps": True,
            "startTimeTicks": 26,
            "width": 27,
            "height": 28,
            "maxWidth": 29,
            "maxHeight": 30,
            "videoBitRate": 31,
            "subtitleStreamIndex": 32,
            "subtitleMethod": "s33",
            "maxRefFrames": 34,
            "maxVideoBitDepth": 35,
            "requireAvc": True,
            "deInterlace": True,
            "requireNonAnamorphic": True,
            "transcodingMaxAudioChannels": 39,
            "cpuCoreLimit": 40,
            "liveStreamId": "s41",
            "enableMpegtsM2TsMode": True,
            "videoCodec": "s43",
            "subtitleCodec": "s44",
            "transcodeReasons": "s45",
            "audioStreamIndex": 46,
            "videoStreamIndex": 47,
            "context": "s48",
            "streamOptions": {"k49": "v49"},
            "enableAudioVbrEncoding": True,
        },
    )

def test_get_master_hls_audio_playlist_required_only_yields_empty_params():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_master_hls_audio_playlist(item_id="item_id-val")
    client.request.assert_called_once()
    args, kwargs = client.request.call_args
    assert args[0] == "GET"
    assert args[1] == "/Audio/item_id-val/master.m3u8"
    assert kwargs["params"] == {}


def test_get_master_hls_audio_playlist_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every optional parameter."""
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_master_hls_audio_playlist(
        item_id="item_id-val",
        static=False,
        stream_params="",
        tag="",
        device_profile_id="",
        play_session_id="",
        segment_container="",
        segment_length=0,
        min_segments=0,
        media_source_id="",
        device_id="",
        audio_codec="",
        enable_auto_stream_copy=False,
        allow_video_stream_copy=False,
        allow_audio_stream_copy=False,
        break_on_non_key_frames=False,
        audio_sample_rate=0,
        max_audio_bit_depth=0,
        max_streaming_bitrate=0,
        audio_bit_rate=0,
        audio_channels=0,
        max_audio_channels=0,
        profile="",
        level="",
        framerate=0.0,
        max_framerate=0.0,
        copy_timestamps=False,
        start_time_ticks=0,
        width=0,
        height=0,
        video_bit_rate=0,
        subtitle_stream_index=0,
        subtitle_method="",
        max_ref_frames=0,
        max_video_bit_depth=0,
        require_avc=False,
        de_interlace=False,
        require_non_anamorphic=False,
        transcoding_max_audio_channels=0,
        cpu_core_limit=0,
        live_stream_id="",
        enable_mpegts_m2_ts_mode=False,
        video_codec="",
        subtitle_codec="",
        transcode_reasons="",
        audio_stream_index=0,
        video_stream_index=0,
        context="",
        stream_options={},
        enable_adaptive_bitrate_streaming=False,
        enable_audio_vbr_encoding=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "static": False,
        "params": "",
        "tag": "",
        "deviceProfileId": "",
        "playSessionId": "",
        "segmentContainer": "",
        "segmentLength": 0,
        "minSegments": 0,
        "mediaSourceId": "",
        "deviceId": "",
        "audioCodec": "",
        "enableAutoStreamCopy": False,
        "allowVideoStreamCopy": False,
        "allowAudioStreamCopy": False,
        "breakOnNonKeyFrames": False,
        "audioSampleRate": 0,
        "maxAudioBitDepth": 0,
        "maxStreamingBitrate": 0,
        "audioBitRate": 0,
        "audioChannels": 0,
        "maxAudioChannels": 0,
        "profile": "",
        "level": "",
        "framerate": 0.0,
        "maxFramerate": 0.0,
        "copyTimestamps": False,
        "startTimeTicks": 0,
        "width": 0,
        "height": 0,
        "videoBitRate": 0,
        "subtitleStreamIndex": 0,
        "subtitleMethod": "",
        "maxRefFrames": 0,
        "maxVideoBitDepth": 0,
        "requireAvc": False,
        "deInterlace": False,
        "requireNonAnamorphic": False,
        "transcodingMaxAudioChannels": 0,
        "cpuCoreLimit": 0,
        "liveStreamId": "",
        "enableMpegtsM2TsMode": False,
        "videoCodec": "",
        "subtitleCodec": "",
        "transcodeReasons": "",
        "audioStreamIndex": 0,
        "videoStreamIndex": 0,
        "context": "",
        "streamOptions": {},
        "enableAdaptiveBitrateStreaming": False,
        "enableAudioVbrEncoding": False,
    }


def test_get_master_hls_audio_playlist_all_params_pass_through_with_camel_case_keys():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_master_hls_audio_playlist(
        item_id="item_id-val",
        static=True,
        stream_params="s1",
        tag="s2",
        device_profile_id="s3",
        play_session_id="s4",
        segment_container="s5",
        segment_length=6,
        min_segments=7,
        media_source_id="s8",
        device_id="s9",
        audio_codec="s10",
        enable_auto_stream_copy=True,
        allow_video_stream_copy=True,
        allow_audio_stream_copy=True,
        break_on_non_key_frames=True,
        audio_sample_rate=15,
        max_audio_bit_depth=16,
        max_streaming_bitrate=17,
        audio_bit_rate=18,
        audio_channels=19,
        max_audio_channels=20,
        profile="s21",
        level="s22",
        framerate=23.5,
        max_framerate=24.5,
        copy_timestamps=True,
        start_time_ticks=26,
        width=27,
        height=28,
        video_bit_rate=29,
        subtitle_stream_index=30,
        subtitle_method="s31",
        max_ref_frames=32,
        max_video_bit_depth=33,
        require_avc=True,
        de_interlace=True,
        require_non_anamorphic=True,
        transcoding_max_audio_channels=37,
        cpu_core_limit=38,
        live_stream_id="s39",
        enable_mpegts_m2_ts_mode=True,
        video_codec="s41",
        subtitle_codec="s42",
        transcode_reasons="s43",
        audio_stream_index=44,
        video_stream_index=45,
        context="s46",
        stream_options={"k47": "v47"},
        enable_adaptive_bitrate_streaming=True,
        enable_audio_vbr_encoding=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Audio/item_id-val/master.m3u8",
        params={
            "static": True,
            "params": "s1",
            "tag": "s2",
            "deviceProfileId": "s3",
            "playSessionId": "s4",
            "segmentContainer": "s5",
            "segmentLength": 6,
            "minSegments": 7,
            "mediaSourceId": "s8",
            "deviceId": "s9",
            "audioCodec": "s10",
            "enableAutoStreamCopy": True,
            "allowVideoStreamCopy": True,
            "allowAudioStreamCopy": True,
            "breakOnNonKeyFrames": True,
            "audioSampleRate": 15,
            "maxAudioBitDepth": 16,
            "maxStreamingBitrate": 17,
            "audioBitRate": 18,
            "audioChannels": 19,
            "maxAudioChannels": 20,
            "profile": "s21",
            "level": "s22",
            "framerate": 23.5,
            "maxFramerate": 24.5,
            "copyTimestamps": True,
            "startTimeTicks": 26,
            "width": 27,
            "height": 28,
            "videoBitRate": 29,
            "subtitleStreamIndex": 30,
            "subtitleMethod": "s31",
            "maxRefFrames": 32,
            "maxVideoBitDepth": 33,
            "requireAvc": True,
            "deInterlace": True,
            "requireNonAnamorphic": True,
            "transcodingMaxAudioChannels": 37,
            "cpuCoreLimit": 38,
            "liveStreamId": "s39",
            "enableMpegtsM2TsMode": True,
            "videoCodec": "s41",
            "subtitleCodec": "s42",
            "transcodeReasons": "s43",
            "audioStreamIndex": 44,
            "videoStreamIndex": 45,
            "context": "s46",
            "streamOptions": {"k47": "v47"},
            "enableAdaptiveBitrateStreaming": True,
            "enableAudioVbrEncoding": True,
        },
    )

def test_get_video_stream_by_container_required_only_yields_empty_params():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_video_stream_by_container(item_id="item_id-val", container="container-val")
    client.request.assert_called_once()
    args, kwargs = client.request.call_args
    assert args[0] == "GET"
    assert args[1] == "/Videos/item_id-val/stream.container-val"
    assert kwargs["params"] == {}


def test_get_video_stream_by_container_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every optional parameter."""
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_video_stream_by_container(
        item_id="item_id-val",
        container="container-val",
        static=False,
        stream_params="",
        tag="",
        device_profile_id="",
        play_session_id="",
        segment_container="",
        segment_length=0,
        min_segments=0,
        media_source_id="",
        device_id="",
        audio_codec="",
        enable_auto_stream_copy=False,
        allow_video_stream_copy=False,
        allow_audio_stream_copy=False,
        break_on_non_key_frames=False,
        audio_sample_rate=0,
        max_audio_bit_depth=0,
        audio_bit_rate=0,
        audio_channels=0,
        max_audio_channels=0,
        profile="",
        level="",
        framerate=0.0,
        max_framerate=0.0,
        copy_timestamps=False,
        start_time_ticks=0,
        width=0,
        height=0,
        max_width=0,
        max_height=0,
        video_bit_rate=0,
        subtitle_stream_index=0,
        subtitle_method="",
        max_ref_frames=0,
        max_video_bit_depth=0,
        require_avc=False,
        de_interlace=False,
        require_non_anamorphic=False,
        transcoding_max_audio_channels=0,
        cpu_core_limit=0,
        live_stream_id="",
        enable_mpegts_m2_ts_mode=False,
        video_codec="",
        subtitle_codec="",
        transcode_reasons="",
        audio_stream_index=0,
        video_stream_index=0,
        context="",
        stream_options={},
        enable_audio_vbr_encoding=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "static": False,
        "params": "",
        "tag": "",
        "deviceProfileId": "",
        "playSessionId": "",
        "segmentContainer": "",
        "segmentLength": 0,
        "minSegments": 0,
        "mediaSourceId": "",
        "deviceId": "",
        "audioCodec": "",
        "enableAutoStreamCopy": False,
        "allowVideoStreamCopy": False,
        "allowAudioStreamCopy": False,
        "breakOnNonKeyFrames": False,
        "audioSampleRate": 0,
        "maxAudioBitDepth": 0,
        "audioBitRate": 0,
        "audioChannels": 0,
        "maxAudioChannels": 0,
        "profile": "",
        "level": "",
        "framerate": 0.0,
        "maxFramerate": 0.0,
        "copyTimestamps": False,
        "startTimeTicks": 0,
        "width": 0,
        "height": 0,
        "maxWidth": 0,
        "maxHeight": 0,
        "videoBitRate": 0,
        "subtitleStreamIndex": 0,
        "subtitleMethod": "",
        "maxRefFrames": 0,
        "maxVideoBitDepth": 0,
        "requireAvc": False,
        "deInterlace": False,
        "requireNonAnamorphic": False,
        "transcodingMaxAudioChannels": 0,
        "cpuCoreLimit": 0,
        "liveStreamId": "",
        "enableMpegtsM2TsMode": False,
        "videoCodec": "",
        "subtitleCodec": "",
        "transcodeReasons": "",
        "audioStreamIndex": 0,
        "videoStreamIndex": 0,
        "context": "",
        "streamOptions": {},
        "enableAudioVbrEncoding": False,
    }


def test_get_video_stream_by_container_all_params_pass_through_with_camel_case_keys():
    client = _make_media_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_video_stream_by_container(
        item_id="item_id-val",
        container="container-val",
        static=True,
        stream_params="s1",
        tag="s2",
        device_profile_id="s3",
        play_session_id="s4",
        segment_container="s5",
        segment_length=6,
        min_segments=7,
        media_source_id="s8",
        device_id="s9",
        audio_codec="s10",
        enable_auto_stream_copy=True,
        allow_video_stream_copy=True,
        allow_audio_stream_copy=True,
        break_on_non_key_frames=True,
        audio_sample_rate=15,
        max_audio_bit_depth=16,
        audio_bit_rate=17,
        audio_channels=18,
        max_audio_channels=19,
        profile="s20",
        level="s21",
        framerate=22.5,
        max_framerate=23.5,
        copy_timestamps=True,
        start_time_ticks=25,
        width=26,
        height=27,
        max_width=28,
        max_height=29,
        video_bit_rate=30,
        subtitle_stream_index=31,
        subtitle_method="s32",
        max_ref_frames=33,
        max_video_bit_depth=34,
        require_avc=True,
        de_interlace=True,
        require_non_anamorphic=True,
        transcoding_max_audio_channels=38,
        cpu_core_limit=39,
        live_stream_id="s40",
        enable_mpegts_m2_ts_mode=True,
        video_codec="s42",
        subtitle_codec="s43",
        transcode_reasons="s44",
        audio_stream_index=45,
        video_stream_index=46,
        context="s47",
        stream_options={"k48": "v48"},
        enable_audio_vbr_encoding=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Videos/item_id-val/stream.container-val",
        params={
            "static": True,
            "params": "s1",
            "tag": "s2",
            "deviceProfileId": "s3",
            "playSessionId": "s4",
            "segmentContainer": "s5",
            "segmentLength": 6,
            "minSegments": 7,
            "mediaSourceId": "s8",
            "deviceId": "s9",
            "audioCodec": "s10",
            "enableAutoStreamCopy": True,
            "allowVideoStreamCopy": True,
            "allowAudioStreamCopy": True,
            "breakOnNonKeyFrames": True,
            "audioSampleRate": 15,
            "maxAudioBitDepth": 16,
            "audioBitRate": 17,
            "audioChannels": 18,
            "maxAudioChannels": 19,
            "profile": "s20",
            "level": "s21",
            "framerate": 22.5,
            "maxFramerate": 23.5,
            "copyTimestamps": True,
            "startTimeTicks": 25,
            "width": 26,
            "height": 27,
            "maxWidth": 28,
            "maxHeight": 29,
            "videoBitRate": 30,
            "subtitleStreamIndex": 31,
            "subtitleMethod": "s32",
            "maxRefFrames": 33,
            "maxVideoBitDepth": 34,
            "requireAvc": True,
            "deInterlace": True,
            "requireNonAnamorphic": True,
            "transcodingMaxAudioChannels": 38,
            "cpuCoreLimit": 39,
            "liveStreamId": "s40",
            "enableMpegtsM2TsMode": True,
            "videoCodec": "s42",
            "subtitleCodec": "s43",
            "transcodeReasons": "s44",
            "audioStreamIndex": 45,
            "videoStreamIndex": 46,
            "context": "s47",
            "streamOptions": {"k48": "v48"},
            "enableAudioVbrEncoding": True,
        },
    )
