"""Characterization tests for LibraryClient.get_items (CXA-FL-JELLYFINMCP-01).

Pins the exact query-parameter construction behaviour of the pre-refactor
CCN-87 function before it is decomposed: every snake_case kwarg maps to a
specific camelCase query key, values are included via ``is not None`` (so
falsy-but-provided values like ``False``/``0``/``""``/``[]`` must survive),
and the request is always a GET to ``/Items``.
"""

from unittest.mock import MagicMock

from jellyfin_mcp.api.api_client_library import LibraryClient


def _make_library_client() -> LibraryClient:
    # ApiBase.__init__ probes /System/Info at construction time but swallows
    # connection errors, so an unreachable base_url is safe here.
    return LibraryClient(base_url="http://127.0.0.1:1/")


def test_get_items_no_params_yields_empty_params():
    client = _make_library_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_items()
    client.request.assert_called_once()
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {}


def test_get_items_falsy_but_not_none_values_are_preserved():
    """Pins the `is not None` (not truthiness) semantics for every parameter."""
    client = _make_library_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_items(
        user_id="",
        max_official_rating="",
        has_theme_song=False,
        has_theme_video=False,
        has_subtitles=False,
        has_special_feature=False,
        has_trailer=False,
        adjacent_to="",
        index_number=0,
        parent_index_number=0,
        has_parental_rating=False,
        is_hd=False,
        is4_k=False,
        location_types=[],
        exclude_location_types=[],
        is_missing=False,
        is_unaired=False,
        min_community_rating=0.0,
        min_critic_rating=0.0,
        min_premiere_date="",
        min_date_last_saved="",
        min_date_last_saved_for_user="",
        max_premiere_date="",
        has_overview=False,
        has_imdb_id=False,
        has_tmdb_id=False,
        has_tvdb_id=False,
        is_movie=False,
        is_series=False,
        is_news=False,
        is_kids=False,
        is_sports=False,
        exclude_item_ids=[],
        start_index=0,
        limit=0,
        recursive=False,
        search_term="",
        sort_order=[],
        parent_id="",
        fields=[],
        exclude_item_types=[],
        include_item_types=[],
        filters=[],
        is_favorite=False,
        media_types=[],
        image_types=[],
        sort_by=[],
        is_played=False,
        genres=[],
        official_ratings=[],
        tags=[],
        years=[],
        enable_user_data=False,
        image_type_limit=0,
        enable_image_types=[],
        person="",
        person_ids=[],
        person_types=[],
        studios=[],
        artists=[],
        exclude_artist_ids=[],
        artist_ids=[],
        album_artist_ids=[],
        contributing_artist_ids=[],
        albums=[],
        album_ids=[],
        ids=[],
        video_types=[],
        min_official_rating="",
        is_locked=False,
        is_place_holder=False,
        has_official_rating=False,
        collapse_box_set_items=False,
        min_width=0,
        min_height=0,
        max_width=0,
        max_height=0,
        is3_d=False,
        series_status=[],
        name_starts_with_or_greater="",
        name_starts_with="",
        name_less_than="",
        studio_ids=[],
        genre_ids=[],
        enable_total_record_count=False,
        enable_images=False,
    )
    _, kwargs = client.request.call_args
    assert kwargs["params"] == {
        "userId": "",
        "maxOfficialRating": "",
        "hasThemeSong": False,
        "hasThemeVideo": False,
        "hasSubtitles": False,
        "hasSpecialFeature": False,
        "hasTrailer": False,
        "adjacentTo": "",
        "indexNumber": 0,
        "parentIndexNumber": 0,
        "hasParentalRating": False,
        "isHd": False,
        "is4K": False,
        "locationTypes": [],
        "excludeLocationTypes": [],
        "isMissing": False,
        "isUnaired": False,
        "minCommunityRating": 0.0,
        "minCriticRating": 0.0,
        "minPremiereDate": "",
        "minDateLastSaved": "",
        "minDateLastSavedForUser": "",
        "maxPremiereDate": "",
        "hasOverview": False,
        "hasImdbId": False,
        "hasTmdbId": False,
        "hasTvdbId": False,
        "isMovie": False,
        "isSeries": False,
        "isNews": False,
        "isKids": False,
        "isSports": False,
        "excludeItemIds": [],
        "startIndex": 0,
        "limit": 0,
        "recursive": False,
        "searchTerm": "",
        "sortOrder": [],
        "parentId": "",
        "fields": [],
        "excludeItemTypes": [],
        "includeItemTypes": [],
        "filters": [],
        "isFavorite": False,
        "mediaTypes": [],
        "imageTypes": [],
        "sortBy": [],
        "isPlayed": False,
        "genres": [],
        "officialRatings": [],
        "tags": [],
        "years": [],
        "enableUserData": False,
        "imageTypeLimit": 0,
        "enableImageTypes": [],
        "person": "",
        "personIds": [],
        "personTypes": [],
        "studios": [],
        "artists": [],
        "excludeArtistIds": [],
        "artistIds": [],
        "albumArtistIds": [],
        "contributingArtistIds": [],
        "albums": [],
        "albumIds": [],
        "ids": [],
        "videoTypes": [],
        "minOfficialRating": "",
        "isLocked": False,
        "isPlaceHolder": False,
        "hasOfficialRating": False,
        "collapseBoxSetItems": False,
        "minWidth": 0,
        "minHeight": 0,
        "maxWidth": 0,
        "maxHeight": 0,
        "is3D": False,
        "seriesStatus": [],
        "nameStartsWithOrGreater": "",
        "nameStartsWith": "",
        "nameLessThan": "",
        "studioIds": [],
        "genreIds": [],
        "enableTotalRecordCount": False,
        "enableImages": False,
    }


def test_get_items_all_params_pass_through_with_camel_case_keys():
    client = _make_library_client()
    client.request = MagicMock(return_value={"ok": True})
    client.get_items(
        user_id="s0",
        max_official_rating="s1",
        has_theme_song=True,
        has_theme_video=True,
        has_subtitles=True,
        has_special_feature=True,
        has_trailer=True,
        adjacent_to="s7",
        index_number=8,
        parent_index_number=9,
        has_parental_rating=True,
        is_hd=True,
        is4_k=True,
        location_types=["v13"],
        exclude_location_types=["v14"],
        is_missing=True,
        is_unaired=True,
        min_community_rating=17.5,
        min_critic_rating=18.5,
        min_premiere_date="s19",
        min_date_last_saved="s20",
        min_date_last_saved_for_user="s21",
        max_premiere_date="s22",
        has_overview=True,
        has_imdb_id=True,
        has_tmdb_id=True,
        has_tvdb_id=True,
        is_movie=True,
        is_series=True,
        is_news=True,
        is_kids=True,
        is_sports=True,
        exclude_item_ids=["v32"],
        start_index=33,
        limit=34,
        recursive=True,
        search_term="s36",
        sort_order=["v37"],
        parent_id="s38",
        fields=["v39"],
        exclude_item_types=["v40"],
        include_item_types=["v41"],
        filters=["v42"],
        is_favorite=True,
        media_types=["v44"],
        image_types=["v45"],
        sort_by=["v46"],
        is_played=True,
        genres=["v48"],
        official_ratings=["v49"],
        tags=["v50"],
        years=["v51"],
        enable_user_data=True,
        image_type_limit=53,
        enable_image_types=["v54"],
        person="s55",
        person_ids=["v56"],
        person_types=["v57"],
        studios=["v58"],
        artists=["v59"],
        exclude_artist_ids=["v60"],
        artist_ids=["v61"],
        album_artist_ids=["v62"],
        contributing_artist_ids=["v63"],
        albums=["v64"],
        album_ids=["v65"],
        ids=["v66"],
        video_types=["v67"],
        min_official_rating="s68",
        is_locked=True,
        is_place_holder=True,
        has_official_rating=True,
        collapse_box_set_items=True,
        min_width=73,
        min_height=74,
        max_width=75,
        max_height=76,
        is3_d=True,
        series_status=["v78"],
        name_starts_with_or_greater="s79",
        name_starts_with="s80",
        name_less_than="s81",
        studio_ids=["v82"],
        genre_ids=["v83"],
        enable_total_record_count=True,
        enable_images=True,
    )
    client.request.assert_called_once_with(
        "GET", "/Items",
        params={
            "userId": "s0",
            "maxOfficialRating": "s1",
            "hasThemeSong": True,
            "hasThemeVideo": True,
            "hasSubtitles": True,
            "hasSpecialFeature": True,
            "hasTrailer": True,
            "adjacentTo": "s7",
            "indexNumber": 8,
            "parentIndexNumber": 9,
            "hasParentalRating": True,
            "isHd": True,
            "is4K": True,
            "locationTypes": ["v13"],
            "excludeLocationTypes": ["v14"],
            "isMissing": True,
            "isUnaired": True,
            "minCommunityRating": 17.5,
            "minCriticRating": 18.5,
            "minPremiereDate": "s19",
            "minDateLastSaved": "s20",
            "minDateLastSavedForUser": "s21",
            "maxPremiereDate": "s22",
            "hasOverview": True,
            "hasImdbId": True,
            "hasTmdbId": True,
            "hasTvdbId": True,
            "isMovie": True,
            "isSeries": True,
            "isNews": True,
            "isKids": True,
            "isSports": True,
            "excludeItemIds": ["v32"],
            "startIndex": 33,
            "limit": 34,
            "recursive": True,
            "searchTerm": "s36",
            "sortOrder": ["v37"],
            "parentId": "s38",
            "fields": ["v39"],
            "excludeItemTypes": ["v40"],
            "includeItemTypes": ["v41"],
            "filters": ["v42"],
            "isFavorite": True,
            "mediaTypes": ["v44"],
            "imageTypes": ["v45"],
            "sortBy": ["v46"],
            "isPlayed": True,
            "genres": ["v48"],
            "officialRatings": ["v49"],
            "tags": ["v50"],
            "years": ["v51"],
            "enableUserData": True,
            "imageTypeLimit": 53,
            "enableImageTypes": ["v54"],
            "person": "s55",
            "personIds": ["v56"],
            "personTypes": ["v57"],
            "studios": ["v58"],
            "artists": ["v59"],
            "excludeArtistIds": ["v60"],
            "artistIds": ["v61"],
            "albumArtistIds": ["v62"],
            "contributingArtistIds": ["v63"],
            "albums": ["v64"],
            "albumIds": ["v65"],
            "ids": ["v66"],
            "videoTypes": ["v67"],
            "minOfficialRating": "s68",
            "isLocked": True,
            "isPlaceHolder": True,
            "hasOfficialRating": True,
            "collapseBoxSetItems": True,
            "minWidth": 73,
            "minHeight": 74,
            "maxWidth": 75,
            "maxHeight": 76,
            "is3D": True,
            "seriesStatus": ["v78"],
            "nameStartsWithOrGreater": "s79",
            "nameStartsWith": "s80",
            "nameLessThan": "s81",
            "studioIds": ["v82"],
            "genreIds": ["v83"],
            "enableTotalRecordCount": True,
            "enableImages": True,
        },
    )
